export const CORE_VERSION = 1;
export * from "./manifest.js";
export * from "./project.js";
export * from "./providers/types.js";
export * from "./stages/deps.js";
export * from "./stages/script.js";
export * from "./stages/shotlist.js";
export * from "./stages/images.js";
export * from "./stages/voiceover.js";
export * from "./stages/assemble.js";
export * from "./music/catalog.js";
